# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-09 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', models.IntegerField(blank=True, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=30)),
                ('DateDeNaissance', models.DateField(blank=True, null=True)),
                ('SalaireSouhaite', models.FloatField(blank=True, null=True)),
                ('Motivation', models.CharField(blank=True, max_length=150)),
                ('DateDeDisponibilite', models.DateField(blank=True, null=True)),
                ('Reponse', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
